/*
 * Copyright (c) 2026 Qualcomm Technologies, Inc. and/or its subsidiaries
 * SPDX-License-Identifier: BSD-3-Clause
 */

#if defined(QCC74X)
#define QC7XX_PERIPHERAL_CPU                    (0)
#define QC7XX_PERIPHERAL_SDU0                   (1)
#define QC7XX_PERIPHERAL_SEC0                   (2)
#define QC7XX_PERIPHERAL_DMA0                   (3)
#define QC7XX_PERIPHERAL_CCI                    (4)
#define QC7XX_PERIPHERAL_GPADC0                 (5)
#define QC7XX_PERIPHERAL_GPDAC0                 (6)
#define QC7XX_PERIPHERAL_TZ1                    (7)
#define QC7XX_PERIPHERAL_TZ2                    (8)
#define QC7XX_PERIPHERAL_EF_CTRL                (9)
#define QC7XX_PERIPHERAL_SF_CTRL                (10)
#define QC7XX_PERIPHERAL_EMAC0                  (11)
#define QC7XX_PERIPHERAL_UART0                  (12)
#define QC7XX_PERIPHERAL_UART1                  (13)
#define QC7XX_PERIPHERAL_UART2                  (14)
#define QC7XX_PERIPHERAL_SPI0                   (15)
#define QC7XX_PERIPHERAL_I2C0                   (16)
#define QC7XX_PERIPHERAL_PWM0                   (17)
#define QC7XX_PERIPHERAL_TIMER0                 (18)
#define QC7XX_PERIPHERAL_IR                     (19)
#define QC7XX_PERIPHERAL_CHECKSUM               (20)
#define QC7XX_PERIPHERAL_I2S0                   (21)
#define QC7XX_PERIPHERAL_PSRAM1_CTRL            (22)
#define QC7XX_PERIPHERAL_USB20                  (23)
#define QC7XX_PERIPHERAL_AUDAC0                 (24)
#define QC7XX_PERIPHERAL_SDH0                   (25)
#define QC7XX_PERIPHERAL_I2C1                   (26)
#define QC7XX_PERIPHERAL_DBI                    (27)
#define QC7XX_PERIPHERAL_AUADC0                 (28)
#define QC7XX_PERIPHERAL_DMA_GPIO               (29)
#define QC7XX_PERIPHERAL_MM_MISC                (30)
#define QC7XX_PERIPHERAL_JENC                   (31)
#define QC7XX_PERIPHERAL_D2XB                   (32)
#define QC7XX_PERIPHERAL_D2XA                   (33)
#define QC7XX_PERIPHERAL_EMI_MISC               (34)
#define QC7XX_PERIPHERAL_CAM0                   (35)
#define QC7XX_PERIPHERAL_RTC                    (36)
#define QC7XX_PERIPHERAL_SEC_PKA                (37)
#define QC7XX_PERIPHERAL_GLB                    (38)
#define QC7XX_PERIPHERAL_SEC_ENG                (39)
#define QC7XX_PERIPHERAL_SEC_DBG                (40)
#define QC7XX_PERIPHERAL_MIX                    (41)
#define QC7XX_PERIPHERAL_PDS                    (42)
#endif

#if defined(QCC75X)
#define QC7XX_PERIPHERAL_CPU                    (0)
#define QC7XX_PERIPHERAL_SDU0                   (1)
#define QC7XX_PERIPHERAL_SEC0                   (2)
#define QC7XX_PERIPHERAL_DMA0                   (3)
#define QC7XX_PERIPHERAL_DMA1                   (4)
#define QC7XX_PERIPHERAL_DMA2                   (5)
#define QC7XX_PERIPHERAL_CCI                    (6)
#define QC7XX_PERIPHERAL_GPADC0                 (7)
#define QC7XX_PERIPHERAL_GPADC1                 (8)
#define QC7XX_PERIPHERAL_GPDAC0                 (9)
#define QC7XX_PERIPHERAL_TZ1                    (10)
#define QC7XX_PERIPHERAL_TZ2                    (11)
#define QC7XX_PERIPHERAL_EF_CTRL                (12)
#define QC7XX_PERIPHERAL_SF_CTRL                (13)
#define QC7XX_PERIPHERAL_EMAC0                  (14)
#define QC7XX_PERIPHERAL_UART0                  (15)
#define QC7XX_PERIPHERAL_UART1                  (16)
#define QC7XX_PERIPHERAL_UART2                  (17)
#define QC7XX_PERIPHERAL_UART3                  (18)
#define QC7XX_PERIPHERAL_SPI0                   (19)
#define QC7XX_PERIPHERAL_SPI1                   (20)
#define QC7XX_PERIPHERAL_I2C0                   (21)
#define QC7XX_PERIPHERAL_I2C1                   (22)
#define QC7XX_PERIPHERAL_I2C2                   (23)
#define QC7XX_PERIPHERAL_PWM0                   (24)
#define QC7XX_PERIPHERAL_TIMER0                 (25)
#define QC7XX_PERIPHERAL_IR                     (26)
#define QC7XX_PERIPHERAL_CHECKSUM               (27)
#define QC7XX_PERIPHERAL_I2S0                   (28)
#define QC7XX_PERIPHERAL_PSRAM1_CTRL            (29)
#define QC7XX_PERIPHERAL_USB20                  (30)
#define QC7XX_PERIPHERAL_AUADC0                 (31)
#define QC7XX_PERIPHERAL_AUDAC0                 (32)
#define QC7XX_PERIPHERAL_SDH0                   (33)
#define QC7XX_PERIPHERAL_DBI                    (34)
#define QC7XX_PERIPHERAL_DMA_GPIO               (35)
#define QC7XX_PERIPHERAL_MM_MISC                (36)
#define QC7XX_PERIPHERAL_GLB                    (37)
#define QC7XX_PERIPHERAL_PDS                    (38)
#define QC7XX_PERIPHERAL_MIX                    (39)
#define QC7XX_PERIPHERAL_SEC_ENG                (40)
#define QC7XX_PERIPHERAL_SEC_DBG                (41)
#define QC7XX_PERIPHERAL_RTC                    (42)
#define QC7XX_PERIPHERAL_JENC                   (43)
#define QC7XX_PERIPHERAL_D2XB                   (44)
#define QC7XX_PERIPHERAL_D2XA                   (45)
#define QC7XX_PERIPHERAL_SEC_PKA                (46)
#define QC7XX_PERIPHERAL_CAM0                   (47)
#define QC7XX_PERIPHERAL_EMI_MISC               (48)
#define QC7XX_PERIPHERAL_PEC                    (49)
#endif

